# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gar's Jekyll Site
description: >- # this means to ignore newlines until "baseurl:"
  Random thoughts, mutterings and musings.

baseurl: jekyll
email: garmail@gmail.com
enable_copy_code_button: true
github_username: garthompson
logo: assets/images/88x88.png
masthead_title: "Gar's scratch-pad"
minimal_mistakes_skin: air
repository: garthompson/jekyll
search: true
site-locale: en-GB
url: https://garthompson.github.io/

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Dublin

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Gar Thompson"
  avatar : "/assets/images/gravatar.jpeg"
  bio    : "Yet another software engineer"
  location: "Kerry, Ireland"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-square-linkedin"
      url: "https://www.linkedin.com/in/garthompson/"
    - label: "GitHub"
      icon: "fab fa-fw fa-square-github"
      url: "https://github.com/garthompson"
    - label: "Bluesky"
      icon: "fab fa-fw fa-square-bluesky"
      url: "https://bsky.app/profile/gar-t.bsky.social"
  since: 2025

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      comments: true
      layout: single
      read_time: true
      related: true
      share: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
